import '@/styles/globals.css'
import Head from 'next/head'
import { GlobalProvider } from '@/providers'

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>New York Times</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com" />
        <link href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet" />
      </Head>
      <GlobalProvider>
        <Component {...pageProps} />
      </GlobalProvider>
    </>
  )
}
